// Generated by the react-native-siri config plugin. Do not edit —
// changes are overwritten on the next `expo prebuild`.
//
// Shared helpers used by the generated App Intents. The JS side of
// react-native-siri writes entity collections into the App Group
// UserDefaults suite; these intents read them natively so Siri can answer
// even while the React Native app is not running.

import Foundation
import UIKit

enum ReactNativeSiriStore {
  static var appGroup: String? {
    Bundle.main.object(forInfoDictionaryKey: "ReactNativeSiriAppGroup") as? String
  }

  static var defaults: UserDefaults? {
    guard let appGroup, !appGroup.isEmpty else {
      return nil
    }
    return UserDefaults(suiteName: appGroup)
  }

  /// Reads a collection previously written by `syncEntities(collection, items)` from JS.
  static func collection(_ name: String) -> [[String: Any]] {
    guard
      let raw = defaults?.string(forKey: "ReactNativeSiri.collection.\(name)"),
      let data = raw.data(using: .utf8),
      let items = (try? JSONSerialization.jsonObject(with: data)) as? [[String: Any]]
    else {
      return []
    }
    return items
  }

  /// Reads a raw value written by `setSharedData(key, value)` from JS.
  static func string(forKey key: String) -> String? {
    defaults?.string(forKey: "ReactNativeSiri.data.\(key)")
  }

  static func stringValue(_ value: Any?) -> String? {
    if let string = value as? String {
      return string
    }
    if let number = value as? NSNumber {
      return number.stringValue
    }
    return nil
  }
}

enum ReactNativeSiriURL {
  private static let allowedCharacters = CharacterSet(
    charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"
  )

  static func encode(_ value: String) -> String {
    value.addingPercentEncoding(withAllowedCharacters: allowedCharacters) ?? value
  }

  /// Opens a deep link back into this app. Generated `action` intents run in
  /// the main app process (`openAppWhenRun = true`), so opening the app's own
  /// URL scheme routes through the normal Linking pipeline into JS.
  @MainActor
  static func open(_ urlString: String) {
    guard let url = URL(string: urlString) else {
      return
    }
    UIApplication.shared.open(url, options: [:], completionHandler: nil)
  }
}
