// Generated by the react-native-siri config plugin. Do not edit —
// changes are overwritten on the next `expo prebuild`.
//
// Shared helpers used by the generated App Intents. The JS side of
// react-native-siri writes entity collections into the App Group
// UserDefaults suite; these intents read them natively so Siri can answer
// even while the React Native app is not running.

import Foundation
import UIKit

enum ReactNativeSiriStore {
  static var appGroup: String? {
    Bundle.main.object(forInfoDictionaryKey: "ReactNativeSiriAppGroup") as? String
  }

  static var defaults: UserDefaults? {
    guard let appGroup, !appGroup.isEmpty else {
      return nil
    }
    return UserDefaults(suiteName: appGroup)
  }

  /// Reads a collection previously written by `syncEntities(collection, items)` from JS.
  static func collection(_ name: String) -> [[String: Any]] {
    guard
      let raw = defaults?.string(forKey: "ReactNativeSiri.collection.\(name)"),
      let data = raw.data(using: .utf8),
      let items = (try? JSONSerialization.jsonObject(with: data)) as? [[String: Any]]
    else {
      return []
    }
    return items
  }

  /// Reads a raw value written by `setSharedData(key, value)` from JS.
  static func string(forKey key: String) -> String? {
    defaults?.string(forKey: "ReactNativeSiri.data.\(key)")
  }

  static func stringValue(_ value: Any?) -> String? {
    if let string = value as? String {
      return string
    }
    if let number = value as? NSNumber {
      return number.stringValue
    }
    return nil
  }
}

enum ReactNativeSiriRemote {
  /// Fetches a collection from a remote HTTPS endpoint at intent time so
  /// Siri answers with live data even when the app has not run in a while.
  /// A successful fetch also replaces the cached collection in the App Group
  /// store, keeping value entities and offline fallbacks current.
  /// Returns nil on any failure; the caller decides whether to fall back.
  static func fetchCollection(
    name: String,
    url: String,
    headersKey: String?,
    timeout: TimeInterval
  ) async -> [[String: Any]]? {
    guard let endpoint = URL(string: url) else {
      return nil
    }
    var request = URLRequest(
      url: endpoint,
      cachePolicy: .reloadIgnoringLocalCacheData,
      timeoutInterval: timeout
    )
    request.setValue("application/json", forHTTPHeaderField: "Accept")
    if
      let headersKey,
      let raw = ReactNativeSiriStore.string(forKey: headersKey),
      let data = raw.data(using: .utf8),
      let headers = (try? JSONSerialization.jsonObject(with: data)) as? [String: String]
    {
      for (field, value) in headers {
        request.setValue(value, forHTTPHeaderField: field)
      }
    }
    do {
      let (data, response) = try await URLSession.shared.data(for: request)
      guard
        let http = response as? HTTPURLResponse,
        (200...299).contains(http.statusCode),
        let items = (try? JSONSerialization.jsonObject(with: data)) as? [[String: Any]]
      else {
        return nil
      }
      if
        let json = try? JSONSerialization.data(withJSONObject: items),
        let jsonString = String(data: json, encoding: .utf8)
      {
        ReactNativeSiriStore.defaults?.set(jsonString, forKey: "ReactNativeSiri.collection.\(name)")
      }
      return items
    } catch {
      return nil
    }
  }
}

enum ReactNativeSiriURL {
  private static let allowedCharacters = CharacterSet(
    charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"
  )

  static func encode(_ value: String) -> String {
    value.addingPercentEncoding(withAllowedCharacters: allowedCharacters) ?? value
  }

  /// Opens a deep link back into this app. Generated `action` intents run in
  /// the main app process (`openAppWhenRun = true`), so opening the app's own
  /// URL scheme routes through the normal Linking pipeline into JS.
  @MainActor
  static func open(_ urlString: String) {
    guard let url = URL(string: urlString) else {
      return
    }
    UIApplication.shared.open(url, options: [:], completionHandler: nil)
  }
}
