import {
  ActionIntentConfig,
  GetIntentConfig,
  QueryIntentConfig,
  ResolvedEntity,
  SiriPluginOptions,
  resolveEntity,
} from './types';

export type GeneratedSwiftFile = {
  filename: string;
  contents: string;
};

const HEADER = `// Generated by the react-native-siri config plugin. Do not edit —
// changes are overwritten on the next \`expo prebuild\`.
`;

function upperFirst(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

/** `arrivalTime` -> `Arrival Time`, `FindTrains` -> `Find Trains` */
function humanize(identifier: string): string {
  return upperFirst(identifier)
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .trim();
}

function escapeForSwiftLiteral(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/**
 * Renders a `${token}` template into a Swift string literal, mapping each
 * token to a Swift interpolation expression.
 */
function renderSwiftLiteral(
  template: string,
  tokens: Record<string, string>,
  context: string
): string {
  const escaped = escapeForSwiftLiteral(template);
  const rendered = escaped.replace(/\$\{([A-Za-z][A-Za-z0-9]*)\}/g, (match, name: string) => {
    const expression = tokens[name];
    if (expression === undefined) {
      throw new Error(
        `[react-native-siri] Unknown template token ${match} in ${context}. ` +
          `Available tokens: ${Object.keys(tokens)
            .map((token) => '${' + token + '}')
            .join(', ')}`
      );
    }
    return `\\(${expression})`;
  });
  return `"${rendered}"`;
}

/** Tokens usable in get/action dialogs and deep links: `${id}` plus every entity field. */
function entityFieldTokens(entity: ResolvedEntity, variableName: string): Record<string, string> {
  const tokens: Record<string, string> = { id: `${variableName}.id` };
  for (const field of entity.fields) {
    tokens[field] = `${variableName}.${field}`;
  }
  return tokens;
}

function entityFieldTokensUrlEncoded(
  entity: ResolvedEntity,
  variableName: string
): Record<string, string> {
  const tokens: Record<string, string> = {
    id: `ReactNativeSiriURL.encode(${variableName}.id)`,
  };
  for (const field of entity.fields) {
    tokens[field] = `ReactNativeSiriURL.encode(${variableName}.${field})`;
  }
  return tokens;
}

export function entityTypeName(entity: ResolvedEntity): string {
  return `${entity.name}Entity`;
}

export function valueEntityTypeName(entity: ResolvedEntity, matchField: string): string {
  return `${entity.name}${upperFirst(matchField)}ValueEntity`;
}

export function entityVariableName(entity: ResolvedEntity): string {
  return lowerFirst(entity.name);
}

/** Distinct matchFields used by query intents (each needs a value entity). */
function queryMatchFields(options: SiriPluginOptions): string[] {
  const fields: string[] = [];
  for (const intent of options.intents) {
    if (intent.type === 'query' && !fields.includes(intent.matchField)) {
      fields.push(intent.matchField);
    }
  }
  return fields;
}

// MARK: entity file

function generateEntityFile(options: SiriPluginOptions): GeneratedSwiftFile {
  const entity = resolveEntity(options.entity);
  const typeName = entityTypeName(entity);
  const queryName = `${typeName}Query`;

  const propertyDeclarations = entity.fields
    .map(
      (field) => `  @Property(title: "${humanize(field)}")
  var ${field}: String`
    )
    .join('\n\n');

  const initParameters = ['id: String', ...entity.fields.map((field) => `${field}: String`)].join(
    ', '
  );
  const initAssignments = ['    self.id = id']
    .concat(entity.fields.map((field) => `    self.${field} = ${field}`))
    .join('\n');

  const fromArguments = [
    '      id: id',
    ...entity.fields.map(
      (field) => `      ${field}: ReactNativeSiriStore.stringValue(item["${field}"]) ?? ""`
    ),
  ].join(',\n');

  const subtitleLine = entity.subtitleField
    ? `DisplayRepresentation(title: "\\(${entity.titleField})", subtitle: "\\(${entity.subtitleField})")`
    : `DisplayRepresentation(title: "\\(${entity.titleField})")`;

  const valueEntities = queryMatchFields(options)
    .map((matchField) => generateValueEntity(entity, matchField))
    .join('\n');

  const contents = `${HEADER}
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct ${typeName}: AppEntity, Identifiable {
  static var typeDisplayRepresentation: TypeDisplayRepresentation = "${escapeForSwiftLiteral(entity.typeDisplayName)}"
  static var defaultQuery = ${queryName}()

  var id: String

${propertyDeclarations}

  var displayRepresentation: DisplayRepresentation {
    ${subtitleLine}
  }

  init(${initParameters}) {
${initAssignments}
  }

  static func from(_ item: [String: Any]) -> ${typeName}? {
    guard let id = ReactNativeSiriStore.stringValue(item["id"]) else {
      return nil
    }
    return ${typeName}(
${fromArguments}
    )
  }

  /// Reads every record synced from JS via \`syncEntities("${entity.collection}", items)\`.
  static func all() -> [${typeName}] {
    ReactNativeSiriStore.collection("${entity.collection}").compactMap { ${typeName}.from($0) }
  }
}

@available(iOS 16.0, *)
struct ${queryName}: EntityStringQuery {
  func entities(for identifiers: [${typeName}.ID]) async throws -> [${typeName}] {
    ${typeName}.all().filter { identifiers.contains($0.id) }
  }

  func entities(matching string: String) async throws -> [${typeName}] {
    ${typeName}.all().filter {
      $0.${entity.titleField}.localizedCaseInsensitiveContains(string) ||
      $0.id.localizedCaseInsensitiveContains(string)
    }
  }

  func suggestedEntities() async throws -> [${typeName}] {
    ${typeName}.all()
  }
}
${valueEntities}`;

  return { filename: `${typeName}.swift`, contents };
}

/**
 * Query intents filter on a field whose values are only known at runtime.
 * Siri phrases may only interpolate AppEntity/AppEnum parameters, so each
 * match field gets a lightweight entity over its distinct values. Type names
 * are intentionally top-level and globally unique (Xcode 16+ requires unique
 * EntityQuery type names across the whole target).
 */
function generateValueEntity(entity: ResolvedEntity, matchField: string): string {
  const typeName = valueEntityTypeName(entity, matchField);
  const queryName = `${typeName}Query`;

  return `
@available(iOS 16.0, *)
struct ${typeName}: AppEntity, Identifiable {
  static var typeDisplayRepresentation: TypeDisplayRepresentation = "${humanize(matchField)}"
  static var defaultQuery = ${queryName}()

  /// The raw field value doubles as the identifier.
  var id: String

  var displayRepresentation: DisplayRepresentation {
    DisplayRepresentation(title: "\\(id)")
  }

  /// Distinct \`${matchField}\` values across the synced collection.
  static func all() -> [${typeName}] {
    var seen = Set<String>()
    var result: [${typeName}] = []
    for item in ReactNativeSiriStore.collection("${entity.collection}") {
      guard let value = ReactNativeSiriStore.stringValue(item["${matchField}"]), !value.isEmpty else {
        continue
      }
      if seen.insert(value).inserted {
        result.append(${typeName}(id: value))
      }
    }
    return result
  }
}

@available(iOS 16.0, *)
struct ${queryName}: EntityStringQuery {
  func entities(for identifiers: [${typeName}.ID]) async throws -> [${typeName}] {
    ${typeName}.all().filter { identifiers.contains($0.id) }
  }

  func entities(matching string: String) async throws -> [${typeName}] {
    ${typeName}.all().filter { $0.id.localizedCaseInsensitiveContains(string) }
  }

  func suggestedEntities() async throws -> [${typeName}] {
    ${typeName}.all()
  }
}
`;
}

// MARK: intent files

function intentBoilerplate(intent: { name: string; title?: string; description?: string }): string {
  const title = intent.title ?? humanize(intent.name);
  const description = intent.description ?? `${humanize(intent.name)} via Siri.`;
  return `  static var title: LocalizedStringResource = "${escapeForSwiftLiteral(title)}"
  static var description = IntentDescription("${escapeForSwiftLiteral(description)}")`;
}

function generateQueryIntent(
  intent: QueryIntentConfig,
  entity: ResolvedEntity
): GeneratedSwiftFile {
  const structName = `${intent.name}Intent`;
  const entityType = entityTypeName(entity);
  const valueType = valueEntityTypeName(entity, intent.matchField);
  const paramVar = intent.matchField;

  const dialogTokens = {
    value: 'matchValue',
    results: 'resultNames',
    count: 'matches.count',
  };
  const usesResults = intent.dialog.includes('${results}');
  const dialogLiteral = renderSwiftLiteral(
    intent.dialog,
    dialogTokens,
    `intents.${intent.name}.dialog`
  );
  const emptyDialogLiteral = renderSwiftLiteral(
    intent.emptyDialog ?? `No matching ${humanize(entity.name).toLowerCase()} items found.`,
    { value: 'matchValue', count: 'matches.count' },
    `intents.${intent.name}.emptyDialog`
  );

  const resultNamesLine = usesResults
    ? `    let resultNames = matches.map { $0.${entity.titleField} }.joined(separator: ", ")\n`
    : '';

  const contents = `${HEADER}
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct ${structName}: AppIntent {
${intentBoilerplate(intent)}

  @Parameter(title: "${humanize(intent.matchField)}")
  var ${paramVar}: ${valueType}

  static var parameterSummary: some ParameterSummary {
    Summary("${escapeForSwiftLiteral(humanize(intent.name))} where ${escapeForSwiftLiteral(humanize(intent.matchField).toLowerCase())} is \\(\\.$${paramVar})")
  }

  func perform() async throws -> some IntentResult & ProvidesDialog & ReturnsValue<[${entityType}]> {
    let matchValue = ${paramVar}.id
    let matches = ${entityType}.all().filter {
      $0.${intent.matchField}.localizedCaseInsensitiveCompare(matchValue) == .orderedSame
    }
${resultNamesLine}    let dialog: IntentDialog = matches.isEmpty
      ? ${emptyDialogLiteral}
      : ${dialogLiteral}
    return .result(value: matches, dialog: dialog)
  }
}
`;
  return { filename: `${structName}.swift`, contents };
}

function generateGetIntent(intent: GetIntentConfig, entity: ResolvedEntity): GeneratedSwiftFile {
  const structName = `${intent.name}Intent`;
  const entityType = entityTypeName(entity);
  const paramVar = entityVariableName(entity);

  const dialogLiteral = renderSwiftLiteral(
    intent.dialog,
    entityFieldTokens(entity, paramVar),
    `intents.${intent.name}.dialog`
  );

  const contents = `${HEADER}
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct ${structName}: AppIntent {
${intentBoilerplate(intent)}

  @Parameter(title: "${escapeForSwiftLiteral(entity.typeDisplayName)}")
  var ${paramVar}: ${entityType}

  static var parameterSummary: some ParameterSummary {
    Summary("${escapeForSwiftLiteral(humanize(intent.name))} for \\(\\.$${paramVar})")
  }

  func perform() async throws -> some IntentResult & ProvidesDialog & ReturnsValue<${entityType}> {
    return .result(value: ${paramVar}, dialog: ${dialogLiteral})
  }
}
`;
  return { filename: `${structName}.swift`, contents };
}

function generateActionIntent(
  intent: ActionIntentConfig,
  entity: ResolvedEntity
): GeneratedSwiftFile {
  const structName = `${intent.name}Intent`;
  const entityType = entityTypeName(entity);
  const paramVar = entityVariableName(entity);

  const deepLinkLiteral = renderSwiftLiteral(
    intent.deepLink,
    entityFieldTokensUrlEncoded(entity, paramVar),
    `intents.${intent.name}.deepLink`
  );

  const dialogLiteral = intent.dialog
    ? renderSwiftLiteral(
        intent.dialog,
        entityFieldTokens(entity, paramVar),
        `intents.${intent.name}.dialog`
      )
    : null;

  const returnType = dialogLiteral ? 'some IntentResult & ProvidesDialog' : 'some IntentResult';
  const returnStatement = dialogLiteral
    ? `return .result(dialog: ${dialogLiteral})`
    : `return .result()`;

  const contents = `${HEADER}
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct ${structName}: AppIntent {
${intentBoilerplate(intent)}

  /// Runs in the main app process and hands off to React Native via deep link.
  static var openAppWhenRun: Bool = true

  @Parameter(title: "${escapeForSwiftLiteral(entity.typeDisplayName)}")
  var ${paramVar}: ${entityType}

  static var parameterSummary: some ParameterSummary {
    Summary("${escapeForSwiftLiteral(humanize(intent.name))} \\(\\.$${paramVar})")
  }

  @MainActor
  func perform() async throws -> ${returnType} {
    ReactNativeSiriURL.open(${deepLinkLiteral})
    ${returnStatement}
  }
}
`;
  return { filename: `${structName}.swift`, contents };
}

// MARK: App Shortcuts provider

function generateAppShortcuts(options: SiriPluginOptions): GeneratedSwiftFile {
  const entity = resolveEntity(options.entity);

  const shortcuts = options.intents
    .map((intent) => {
      const paramVar = intent.type === 'query' ? intent.matchField : entityVariableName(entity);
      const phrases = intent.phrases
        .map((phrase) =>
          renderSwiftLiteral(
            phrase,
            {
              appName: '.applicationName',
              param: `\\.$${paramVar}`,
            },
            `intents.${intent.name}.phrases`
          )
        )
        .map((literal) => `        ${literal},`)
        .join('\n');
      return `    AppShortcut(
      intent: ${intent.name}Intent(),
      phrases: [
${phrases}
      ]
    )`;
    })
    .join('\n');

  const contents = `${HEADER}
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct ReactNativeSiriAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
${shortcuts}
  }
}

/// Bridge for the react-native-siri pod: the pod cannot import app-target
/// types, so it reaches this class through \`NSClassFromString\` after every
/// data sync to re-register the App Shortcut phrase parameters with Siri.
@objc(ReactNativeSiriShortcutsHelper)
public final class ReactNativeSiriShortcutsHelper: NSObject {
  @objc public static func updateAppShortcutParameters() {
    if #available(iOS 16.0, *) {
      ReactNativeSiriAppShortcuts.updateAppShortcutParameters()
    }
  }
}
`;
  return { filename: 'ReactNativeSiriAppShortcuts.swift', contents };
}

// MARK: entry point

/**
 * Generates every Swift file for the app target (deterministic — used both to
 * write files in `withDangerousMod` and to register them in the pbxproj).
 */
export function generateSwiftFiles(options: SiriPluginOptions): GeneratedSwiftFile[] {
  const entity = resolveEntity(options.entity);
  const files: GeneratedSwiftFile[] = [generateEntityFile(options)];

  for (const intent of options.intents) {
    if (intent.type === 'query') {
      files.push(generateQueryIntent(intent, entity));
    } else if (intent.type === 'get') {
      files.push(generateGetIntent(intent, entity));
    } else {
      files.push(generateActionIntent(intent, entity));
    }
  }

  files.push(generateAppShortcuts(options));
  return files;
}
