/**
 * A single entity record synced to the App Group store so that the generated
 * App Intents (compiled into the main app target) can read it while the
 * React Native app is not running.
 *
 * Every record must have a unique, stable `id`. All other values are
 * stringified before being handed to the native side, because the generated
 * Swift entities model every field as a `String`.
 */
export type SiriEntityRecord = {
  id: string;
  [field: string]: string | number | boolean | null | undefined;
};

export type DonateUserActivityOptions = {
  /**
   * Reverse-DNS activity type, e.g. `com.example.app.viewing`.
   * Must be listed in the app's `NSUserActivityTypes` (the config plugin adds
   * the types you pass via the `userActivityTypes` option, and by default
   * registers `<bundleIdentifier>.viewing`).
   */
  activityType: string;
  /** User-visible title, e.g. `Train RMEGR`. */
  title: string;
  /** Arbitrary payload restored when the activity is continued. */
  userInfo?: Record<string, string>;
  /** Extra Spotlight keywords. */
  keywords?: string[];
  /** Stable identifier so repeated donations of the same content coalesce. */
  persistentIdentifier?: string;
  /** Defaults to true. */
  eligibleForSearch?: boolean;
  /** Defaults to true. Allows Siri/Shortcuts to predict this activity. */
  eligibleForPrediction?: boolean;
};

/**
 * Parsed deep link the app was opened with. Action intents generated by the
 * config plugin open the app through their configured `deepLink` template,
 * so this is how JS learns that Siri ran an action.
 */
export type IntentLaunchEvent = {
  /** The full URL, e.g. `trains://follow?id=RMEGR`. */
  url: string;
  /** URL scheme, e.g. `trains`. */
  scheme: string | null;
  /** Host portion, e.g. `follow`. */
  host: string | null;
  /** Path portion without leading slash, e.g. `` or `details`. */
  path: string | null;
  /** Decoded query parameters, e.g. `{ id: 'RMEGR' }`. */
  params: Record<string, string>;
};

export type IntentListenerSubscription = {
  remove(): void;
};
